name: Tests with jest and postgres db

on: 
  pull_request: 
    branches:
      - master
      - develop
      - staging

jobs:
  # Label of the container job
  container-db: 
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test
        env:
          DB_USERNAME: postgres
          DB_HOST: postgres
          DB_NAME: postgres
          DB_PWD: postgres


